In [3]:
import numpy as np
import math
from numpy import linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a = np.array([[1,2], [3,4]])
b = np.array([2,1])

a * b

array([[2, 2],
       [6, 4]])

In [3]:
np.matmul(a, b)

array([ 4, 10])

In [4]:
b = np.arange(9).reshape((3,3))
va, ve = la.eig(b)

In [5]:
diag = np.diag(va)
inv = la.inv(ve)

In [6]:
c=np.matmul(diag, inv)

In [7]:
c=np.matmul(ve, c).astype(int)

In [8]:
b ==c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
d = np.matmul(ve, diag)
d = np.matmul(d, inv).astype(int)
d==b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
d == c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
np.matmul(ve, inv).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
diag.astype(int)

array([[13,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  0]])

In [13]:
e = np.matmul(ve, inv)
e = np.matmul(e, diag).astype(int)
e

array([[13,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  0]])